// Code generated by "stringer -type=PrimitiveType -output=types_string.go"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[Uint8-1]
	_ = x[Uint16-2]
	_ = x[Uint32-3]
	_ = x[Uint64-4]
	_ = x[Int8-5]
	_ = x[Int16-6]
	_ = x[Int32-7]
	_ = x[Int64-8]
	_ = x[Float32-9]
	_ = x[Float64-10]
	_ = x[Bool-11]
	_ = x[String-12]
}

const _PrimitiveType_name = "InvalidUint8Uint16Uint32Uint64Int8Int16Int32Int64Float32Float64BoolString"

var _PrimitiveType_index = [...]uint8{0, 7, 12, 18, 24, 30, 34, 39, 44, 49, 56, 63, 67, 73}

func (i PrimitiveType) String() string {
	if i < 0 || i >= PrimitiveType(len(_PrimitiveType_index)-1) {
		return "PrimitiveType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PrimitiveType_name[_PrimitiveType_index[i]:_PrimitiveType_index[i+1]]
}
